version: '3.8'

services:
  backend:
    container_name: notoli-backend
    image: ghcr.io/vanillaicecube/notoli-backend:latest
    volumes:
      - ./db.sqlite3:/backend/db.sqlite3
    ports:
      - "8000:8000"
    env_file: .env
    restart: always

  frontend:
    container_name: notoli-frontend
    image: ghcr.io/vanillaicecube/notoli-frontend:latest
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
