name: notoli_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - pip
  - pip:
      - -r requirements.txt

# Update env + requirements.txt (pip packages go into requirements.txt)
# `python backend/environment_conda_export.py --from-history --use-versions -o backend/environment.yml`
# Overwrite environment from yaml
# `conda env update --file backend/environment.yml --prune`
