version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: notoli-proxy
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - frontend
      - backend

  backend:
    image: ghcr.io/vanillaicecube/notoli-backend:latest
    container_name: notoli-backend
    volumes:
      - ./db.sqlite3:/backend/db.sqlite3
    ports:
      - "8000:8000"
    env_file: .env
    restart: always

  frontend:
    image: ghcr.io/vanillaicecube/notoli-frontend:latest
    container_name: notoli-frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
